### PR TITLE
Adds compatability for Laravel 6

### PR DESCRIPTION
**Pull request by djfrailey**
*Issue #, if available:* #168 

*Description of changes:*
Added ~6.0 to the list of allowed versions for the illuminate\support package.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by munir131** [comment]
@djfrailey Test cases are failing for lumen. You need to change makefile

**Comment by duellsy** [comment]
Any updates here? Currently blocking us on a few projects from upgrading. 

I'd be happy to help, but not sure what needs to change in the Makefile

**Comment by djfrailey** [comment]
@munir131 Sorry for the late reply everyone.

I'll need a little more direction than that, I'm not too sure what needs to happen to the Makefile in order to make Lumen play nice with Laravel's 6.0 components.

**Comment by howardlopez** [comment]
@djfrailey Thanks for the PR! I played around with this a bit and was able to get the Travis tests passing in #170. Looks like the distribution had to be changed for PHP 5.5 as well. Will also update here when it's merged.

**Comment by howardlopez** [comment]
#170 has been merged, so I'll go ahead and close this one out.

**Pull request closed without merging**
