### PR TITLE
Upgrade aws sdk to upgrade guzzle

### PR DESCRIPTION
**Pull request by astrojason**
guzzle/guzzle has been abandoned

### CODE REVIEW

**Comment by cjyclaire** [comment]
@astrojason We do have [support](https://github.com/aws/aws-sdk-php-laravel/blob/master/README.md) for SDK V3 in all v3 release for `aws-sdk-php-laravel`

**Comment by astrojason** [comment]
This is for the v1, laravel 4 branch

**Comment by douglasmiguel** [comment]
Yes, please.
I have the same problem.

"Package guzzle/guzzle is abandoned, you should avoid using it. Use guzzlehttp/guzzle instead."

**Comment by cjyclaire** [comment]
@astrojason Okay, before I merged the changes and tag a release, in consideration of backwards-compatibility, could you also change the [version constant](https://github.com/aws/aws-sdk-php-laravel/blob/1.0/src/Aws/Laravel/AwsServiceProvider.php#L31) to have a minor version bump that in case this might break someone?

**Comment by astrojason** [comment]
@cjyclaire Updated version constant

**Comment by cjyclaire** [comment]
@astrojason Great, thanks!

**Comment by GrahamCampbell** [comment]
This is a major breaking change to 1.x though?

**Comment by cjyclaire** [comment]
That's true, I revert the change, fix the tag.

@astrojason Considering it's a major break, in terms of using `aws-sdk-php` v3, it's better practice to use compatible `laravel` version according to README.md.

**Pull request merged**
