### PR TITLE
Bump dependencies to allow for Laravel 9

### PR DESCRIPTION
**Pull request by jdanino**
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by etelford** [comment]
It would be great to get this merged!

**Comment by vitorn1234** [comment]
yep trying to update to 9.0 and this is breaking stuff :D

**Comment by mchorsley** [comment]
@jdanino Could you update the README.md to show support for Laravel 9?  May help to get the PR merged. Thanks for updating composer.json.

**Review by vitorn1234 — APPROVED** [review]

**Comment by SamRemis** [comment]
Hi there, I'm from amazon.  Gonna talk to the team about it during a meeting tomorrow and try to get this on the docket soon.  If you'd like to reach us, I try to respond on [gitter](https://gitter.im/aws/aws-sdk-php) as quickly as I can, and tagging me helps me to see it sooner.

**Review by Superkooka — APPROVED** [review]

**Review by SpartakusMd — APPROVED** [review]

**Comment by 82rules** [comment]
Would love to see this in asap!! this is a blocker for us upgrading to Laravel 9

**Comment by lucca257** [comment]
please, accept the merge request asap! I can`t upgrade my project for laravel 9

**Comment by SamRemis** [comment]
[This PR](https://github.com/aws/aws-sdk-php-laravel/pull/207) was also asking for the same thing; unfortunately this is a breaking change and we need to bump our minimum and maximum supported versions, which will take some time.  We are discussing it now and working on making a final decision and then shortly thereafter will make an official public announcement if we do.  
It's frustrating that this is holding people back from upgrading their versions, so I consider this a high priority.  It's looking like we will be dropping support for 5.5, 5.6, and 7.0, so after we make the announcement, we need to give customers on those versions some time to upgrade.  Since this is holding people back from upgrading, I will  float the idea of fast-tracking this repo and the symfony repo in order to support the newest versions.

**Comment by hailwood** [comment]
@SamRemis Why do you need to give customers on those older versions time to upgrade.
They can just continue to use the current version of the given packages until they're ready to upgrade, it's not like releasing a new version unpublished old versions.

**Comment by NickBourque** [comment]
> @SamRemis Why do you need to give customers on those older versions time to upgrade? They can just continue to use the current version of the given packages until they're ready to upgrade, it's not like releasing a new version unpublished old versions.

@SamRemis - I, too, am curious about this. Why not tag a new version for this release now and drop support for old versions later? Getting an important release out shouldn't be dependent on when you can drop support for old versions. This is very important to us, and I would love to see this merged asap.

**Comment by cy8urg** [comment]
@SamRemis - Very important for me and my guys as well, why can you not release for 9 and let others upgrade as and when they need/want...? Please merge this...

**Comment by SamRemis** [comment]
I may be able to merge this one sooner, but I have to at least get to the point of officially announcing the deprecation campaign.  This is one of my highest priorities since it's clearly important to the community, but this PR won't be merged unless it is updated to have the necessary changes; when I'm able, I will make my own PR that fixes the breaking changes.  I'm leaving this PR up only as a place for updates and to keep the history of this conversation in one place.  

It's a fair bit of work to write and test something like this with a new version.  It's not just pressing a merge button.  If I were to merge this, it would likely break code. This needs unit test refactoring, versioning changes, function changes, and most likely a major version change.

**Comment by jonnylink** [comment]
>It's a fair bit of work to write and test something like this with a new version. It's not just pressing a merge button. If I were to merge this, it would likely break code. This needs unit test refactoring, versioning changes, function changes, and most likely a major version change.

None of that makes any sense. This is a trivial change. The change here is just saying that it works with Laravel 9. It does.

**Comment by NickBourque** [comment]
> >It's a fair bit of work to write and test something like this with a new version. It's not just pressing a merge button. If I were to merge this, it would likely break code. This needs unit test refactoring, versioning changes, function changes, and most likely a major version change.
> 
> None of that makes any sense. This is a trivial change. The change here is just saying that it works with Laravel 9. It does.

Yeah I don't get it either. It's impossible to introduce a backward compatibility issue by merging this PR because all this is doing is saying "hi I work with Laravel 9", which is true with zero other code changes.

**Comment by jonnylink** [comment]
Yeah definitely not a breaking change of any kind. I appreciate the guy looking in on this, but he doesn't seem to get what the ask is here.

**Comment by shawnlindstrom** [comment]
@howardlopez merged the release to support Laravel 8. Maybe he can help?

**Comment by SamRemis** [comment]
I deleted a comment tagging someone who no longer works for amazon

**Comment by massimodellarovere** [comment]
I have been a passionate user of Amazon Web Service and PHP development for many years. Unfortunately, the combination of AWS and PHP is a problem that has always been there and seems unsolvable. Amazon doesn't like PHP... It's is True..

```php
dump( $amazon->likephp()  ) = false
```

**Comment by NickBourque** [comment]
> I deleted a comment tagging someone who no longer works for amazon

Could've spent that 3 seconds hitting the merge button and still had a second to spare

**Comment by jonnylink** [comment]
@SamRemis I appreciate that you are taking this seriously, and I'm sorry to push like this, but you're actually creating an unnecessary headache for AWS customers in this case. You do realize this is the Laravel package and not the PHP SDK itself, right? If so, can you please explain why you believe changing the composer requirements to allow Laravel 9 impacts any past version of Laravel? 

We are literally talking about four files here: a facade, a service provider, and some config stuff that get overwritten anyway. Comments removed we are looking at less than 100 lines of code. Nothing in Laravel 9 has changed that would lead to any code changes.

**Comment by SamRemis** [comment]
@jonnylink thanks for understanding and patience; looks like my initial assessment of the significance was probably incorrect.  I still need time to do my due diligence. This will be my first priority and I'll work on it as soon as I'm able, which is early next week.

If what I've read so far from the docs is a good indicator, it shouldn't take long at all once I've started.

**Comment by SpartakusMd** [comment]
Thank you @SamRemis for helping us with moving forward on this. As this is a library used by many, proper checks should be done and we understand it.

If it helps, we forked the project and made same changes as in this PR (basically allowing use of Laravel 9). We already use it in production on a couple of core projects. No issues found so far.

**Comment by jonnylink** [comment]
Thanks for making a second assessment, @SamRemis. When you get down to it, this package is really just a service provider for the SDK. As you can see in the [upgrade guide](https://laravel.com/docs/9.x/upgrade) there aren't any changes to the service providers, so there truly isn't anything to do. The unit tests as written should adequately cover things. Looking forward to this getting pushed out next week.

**Review by MarkVaughn — APPROVED** [review]

**Comment by goyote** [comment]
MERGE THIS!

**Comment by etelford** [comment]
I know this is annoying and inconvenient for some of us, but please be kind. You aren't without temporary or even permanent alternate solutions (like forking, creating your own service provider, etc.) if upgrading to Laravel 9 is that important to you.

**Comment by jonnylink** [comment]
> I know this is annoying and inconvenient for some of us, but please be kind. You aren't without temporary or even permanent alternate solutions (like forking, creating your own service provider, etc.) if upgrading to Laravel 9 is that important to you.

I agree there's no need for rudeness. On the other hand I think it's quite justifiable for paying AWS customers to be upset that this incredibly simple PR has languished for more than a month. 

If AWS doesn't want to support the package, they should archive the project and be done with it. At least people wouldn't make the mistake of believing it'll get reasonable support because, as you noted, it isn't impossible to work around it.

It definitely doesn't make me feel optimistic about the future of support for the PHP SDK if we can't even get `||^9.0` added to a single line of a composer file within a reasonable time. Laravel 9 was original supposed to be release in Sept 2021, so it isn't like this just came out of nowhere.

...meh. I think I just convinced myself to drop this package.

**Comment by jonnylink** [comment]
Counter point: It seems pretty clear that this package (and AWS customers) aren't going to get the support at a professional level. This PR literally just adds `||^9.0` to a single line. If that takes over a month it's time for AWS to archive the package so that someone else can carry the torch.

**Comment by hailwood** [comment]
@jonnylink Just because the aws package exists doesn't stop you from publishing your own on packagist if you feel that way.

image

**Comment by jonnylink** [comment]
@hailwood off-topic. The PR is good and should have been merged a month ago.

AWS doesn't need you rushing to the defense their defense, they are a company with an annual revenue or $71B. This isn't an group of volunteers it's a company poorly supporting a product used by its customers.

**Comment by massimodellarovere** [comment]
Waiting all this time for such a simple change is truly incredible. The answers of some of those responsible are ridiculous and do not deserve a debate. As for me I can also wait, I will move the update of my AWS customers to next month, but in the meantime I have presented to AWS Support as a premium user with 35 midrange customers my due reflections.

**Comment by SamRemis** [comment]
Resolved by https://github.com/aws/aws-sdk-php-laravel/pull/209

**Pull request closed without merging**
