### PR TITLE
Fix Lumen support

### PR DESCRIPTION
**Pull request by jeskew**
Merge in #91 and add test for Lumen support.

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
@jeskew I wouldn't rely on this working in the future. We intended make composer prevent installing laravel and lumen at the same time, but never added the restriction.

**Comment by GrahamCampbell** [comment]
The reason being the global functions conflict with each other and totally screw everything up.

**Comment by jeskew** [comment]
@GrahamCampbell That's unfortunate. I guess I could have Travis uninstall Laravel and install Lumen in response to an environment variable.

**Comment by GrahamCampbell** [comment]
That would work, yes, and then have the tests conditionally skip on class existance.

**Pull request merged**
