### PR TITLE
Add Laravel 8 support

### PR DESCRIPTION
**Pull request by Kussie**
*Description of changes:*
Adds support for Laravel 8

*Changes:*
 - Bump supported version of Illuminate/support to ^8.0
 - Bump the version of dotenv to include support for ^5.0
 - Update docs to show support for Laravel 8

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by flemzord** [comment]
Laravel 8 is out :)

**Comment by Kussie** [comment]
All green and ready to go

**Comment by likeadeckofcards** [comment]
When will this be merged?

**Comment by byteasc** [comment]
+1

**Comment by huangdijia** [comment]
+1

**Comment by sidigi** [comment]
+1

**Comment by SamRemis** [comment]
This needs a changelog, once it is added, it shouldn't take long to merge

**Comment by Kussie** [comment]
@SamRemis This change is almost the same as the Laravel 7 support branch that was merged (Apart from version numbers).  I can add the changes to the changelog.md if that is what you asking, but imho that should be done when a new version is tagged instead, which this is not doing.

**Comment by duellsy** [comment]
@SamRemis Agree with @Kussie on this one, the `CHANGELOG.md` and the version number should only be bumped when the release is actually tagged, not as part of a PR, as it was with the `3.5.0` release: https://github.com/aws/aws-sdk-php-laravel/commit/7a3705461c06dc1ce8496fbf9b22ec96f769b3a7

Are you able to handle this? It's holding up a lot of Laravel 8 upgrades :)

**Comment by duellsy** [comment]
Also tagging @howardlopez for input as they did the last couple of tagged releases 👋

**Comment by Cannonb4ll** [comment]
Waiting for this as well 👍

**Comment by martinduefrandsen** [comment]
When will this be merged?

**Review by howardlopez — APPROVED** [review]
Thanks fore the PR @Kussie!

**Comment by howardlopez** [comment]
[Version 3.6.0](https://github.com/aws/aws-sdk-php-laravel/releases/tag/3.6.0) has been released with the changes. We appreciate your work on this @Kussie!

**Pull request merged**
