### PR TITLE
Updated to support both laravel 4 and laravel 5

### PR DESCRIPTION
**Pull request by GrahamCampbell**
This makes sure we're compatible with all versions of laravel 4 and laravel 5.

I've also updated to phpunit 4, and moved to psr-4 without modifying the directory structure.

### CODE REVIEW

**Comment by KennedyTedesco** [comment]
:+1:

**Comment by swvjeff** [comment]
Can this be merged now that Laravel 5 has been released?

**Comment by alairock** [comment]
+1 PLZ

**Comment by alairock** [comment]
I also wouldn't be apposed to making GrahamCampbell an official maintainer of the repo ;)

**Comment by jeremeamia** [comment]
@KennedyTedesco @swvjeff @alairock Have you confirmed that these changes work for Laravel 5?

@GrahamCampbell Is this all that needs to be done?

**Comment by alairock** [comment]
Works for me.

**Comment by rdehnhardt** [comment]
+1 Plz! To!


Renato Dehnhardt

renato@fullsystem.com.br

fullsystem.com.br <http://www.fullsystem.com.br>

(041) 9277.4748

  <http://facebook.com/fullsystembrasil> <http://fullsystem.com.br/>

2015-02-05 14:14 GMT-02:00 Skyler Lewis <notifications@github.com>:

**Comment by tomschlick** [comment]
While these changes are a step forward, L5 removes the $this->package() method in the service provider and handles configuration a little differently. 

So this will still work for L4 but L5 requires more changes and probably a separate branch/tag on the repo as the L5 changes wont be backwards compatible with L4.

**Comment by jeremeamia** [comment]
I'm getting mixed feedback on this PR. @GrahamCampbell and @tomschlick, what needs to be done to make this correct? It seems like the changes may not be enough to support L5. Will we need to tag a new major release?

**Comment by tomschlick** [comment]
Yes it would need a new major release. L5 is a breaking change in how packages load and publish configs.

If it makes it easier, i can just create a new PR with the changes @GrahamCampbell did and get it all working within one.

**Comment by jeremeamia** [comment]
Yeah, that would be great @tomschlick. Thanks. It looks like from the docs that `$this->app->singleton()` is favored now. Also, should the L5 provider be deferred?

**Comment by tomschlick** [comment]
From everything I'm seeing it could be deferred. If it in fact can be I'll make it so in the PR.

**Comment by arcadas** [comment]
+1

**Comment by tomschlick** [comment]
By the way, #52 has the changes we were talking about above.

**Comment by GrahamCampbell** [comment]
@jeremeamia This pull is broken on 5.0 in it's current state due to it's use of the package method.

I suggest creating a totally new branch for L5 and not trying to support L4 and L5 at the same time.

**Comment by jeremeamia** [comment]
Closing this in favor of #52

**Pull request closed without merging**
