### PR TITLE
Allow loading of SDK via Dependency Injection

### PR DESCRIPTION
**Pull request by mattzuba**
I avoid the use of Facades in my application as much as possible, leveraging Laravels IoC/DI capabilities to load classes throughout my application. This change would more easily facilitate that.

### CODE REVIEW

**Comment by jeremeamia** [comment]
You'll have to explain this better. What does this do, and why does it solve your problem?

**Comment by GrahamCampbell** [comment]
@jeremeamia This means people can typehint the class, and the laravel container will be able to automatically resolve it. Without this addition, the following code won't work:


```php
<?php

use Aws\Common\Aws;

class Foo
{
    protected $aws;

    public function __constructor(Aws $aws)
    {
        $this->aws = $aws;
    }
}

var_dump(app()->make('Foo'));
```

**Comment by mattzuba** [comment]
Thanks @GrahamCampbell!

@jeremeamia To give a little more detail if you're not familiar with Laravel's loading pattern, when Laravel loads a class via it's Container, it uses PHP's Reflection API to introspect the constructor and automatically and recursively populate type hinted dependencies.  Without my change, if you used @GrahamCampbell's example, it would fail because it would try to create a new instance of the Aws\Common\Aws class.  With my change, Laravel's container will see that I want to load Aws\Common\Aws and see if there is a mapping from that to an alias (in this case, 'aws') and load the already created object from the Service Provider.

**Comment by jeremeamia** [comment]
Sounds good to me.

**Comment by zanematthew** [comment]
Whats the correct syntax for leveraging Laravel container? I've tried the following:

```
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Requests;
use \AWS;

class FooController extends Controller
{
    public function __construct( AWS $aws )
    {
        dd( get_class_methods( $aws ) );
    }

}

```

I do have the class added to my `config/app.php` providers as `        Aws\Laravel\AwsServiceProvider::class,
`, and aliases as `'AWS' => Aws\Laravel\AwsFacade::class,`

The above code returns the following:
```
array:8 [▼
  0 => "swap"
  1 => "shouldReceive"
  2 => "getFacadeRoot"
  3 => "clearResolvedInstance"
  4 => "clearResolvedInstances"
  5 => "getFacadeApplication"
  6 => "setFacadeApplication"
  7 => "__callStatic"
]
```

Note that calling the class statically does work, however when I try to inject it does not.

Any help would be greatly appreciated, I'm knew to Laravel, however I'm picking it up quick, and liking it thus far.

**Comment by mattzuba** [comment]
The correct `use` statement would be

`use Aws\Common\Aws ;`

You don't want to inject the façade, you want to inject what the façade resolves to.

**Comment by zanematthew** [comment]
@matt thanks for clarifying, I was having issues with `use Aws\Common\Aws;` figured it might be related to a [composer issue](http://stackoverflow.com/questions/21785217/aws-sdk-for-laravel-giving-php-fatal-error#).

Also found issue #58 to be informative as well. I'll confirm this works this evening.

**Comment by zanematthew** [comment]
Seems this might be related to a composer issue, here's my full file. I have a simple line in `routes.php`, which is `Route::get('/foo', 'Foo@index');`

```php

<?php
namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Requests;
use Aws\Common\Aws;


class Foo extends Controller
{
    protected $aws;

    public function __construct(Aws $aws)
    {
        $this->aws = $aws;
        dd($aws);
    }

    public function index()
    {
        //
    }
}
```

My log is showing
`ReflectionException in Container.php line 798:
Class Aws\Common\Aws does not exist`. I'd love to know what the issue is.

**Comment by jeskew** [comment]
@zanematthew If you're using a 3.x release of this package, you should inject `Aws\Sdk` instead.

**Comment by zanematthew** [comment]
Thanks, so should the correct usage be? As this is still throwing the class does not exists.

```php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Requests;
use Aws\Sdk\Aws;

class FooController extends Controller
{
    protected $aws;

    public function __construct( Aws $aws)
    {
        $this->aws = $aws;        
    }

    public function index()
    {
        //
    }
}
```

Note, if I just throw this into my controller this works all day:

```$this->s3 = \AWS::createClient('s3');```

**Comment by jeskew** [comment]
Sorry if that was unclear; the class (not the namespace) is named [`Aws\Sdk`](https://docs.aws.amazon.com/aws-sdk-php/v3/guide/getting-started/basic-usage.html#using-the-sdk-class)

**Comment by zanematthew** [comment]
Word :+1: the below code is it.

```php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Requests;


class FooController extends Controller
{
    protected $aws;

    public function __construct( \Aws\Sdk $aws)
    {
        $this->aws = $aws;
        dd($this->aws);
    }

    public function index()
    {
        //
    }
}
```

The output.

```
Sdk {#341 ▼
  -args: array:5 [▼
    "credentials" => array:2 [▶]
    "region" => "us-east-1"
    "version" => "latest"
    "ua_append" => array:1 [▶]
    "http_handler" => GuzzleHandler {#342 ▶}
  ]
}
```

Thanks, again for the patience, would have no idea about the `Aws\Sdk $aws`. Hopefully these comments will aid others that have the same issue. 

Possibly consider updating the documentation with this?

**Comment by GrahamCampbell** [comment]
Or, just:

```
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Requests;
use Aws\Sdk;

class FooController extends Controller
{
    protected $aws;

    public function __construct(Sdk $aws)
    {
        $this->aws = $aws;
        dd($this->aws);
    }

    public function index()
    {
        //
    }
}
```

**Comment by zanematthew** [comment]
@GrahamCampbell @jeskew Laravel is new to me, can you fill me in on how you know to use `use Aws\Sdk;` considering it is not mentioned in the docs?

**Comment by GrahamCampbell** [comment]
The `use` statement has nothing to do with Laravel. It's a native PHP construct.

**Comment by zanematthew** [comment]
@GrahamCampbell I'm aware of the `use` statement in PHP :) I'm specifically referring to how you used  [Aws\Common](https://github.com/aws/aws-sdk-php-laravel/pull/51#issuecomment-73913829) but @gokarnm said it should have been [Aws\Sdk](https://github.com/aws/aws-sdk-php-laravel/pull/51#issuecomment-217746747).

**Comment by jeskew** [comment]
You can find the documentation on using an instance of `Aws\Sdk` [here](https://docs.aws.amazon.com/aws-sdk-php/v3/guide/getting-started/basic-usage.html#using-the-sdk-class).

**Comment by zanematthew** [comment]
@jeskew Thank you.

**Pull request merged**
